apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-server
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
